### ISSUE TITLE
Can't run mod on rented servers ~ 

### ISSUE THREAD

**Issue by Kayjichu** [s0t7x/shroudtopia#6]
So im renting a server off a site and when drag and drop into the server folder, the mod doesn't load up. I also test it out on the steam server tool version and it worked fine...I'm aware it might be because of how the rented server is setup, but if there's any workaround or fixes for this, I'd greatly appreciate it!
![62e493851cf31ae660b0e7d39b3b7408](https://github.com/user-attachments/assets/d98c05f5-2b0a-4800-9aa9-240058b5f2a9)

usually it would indicate that the mod is loaded at the top, but this is what I get on my rented server instead.

**Comment by s0t7x** [comment]
what you see is output from steamcmd. Looking at what it states it looks like your server is getting started via proton which indicates its running on linux. You may have to fiddle with your server setup to get to the place where you actually have to put the mod files.
